
import type { Project } from './types';

export const projectsData: Project[] = [
  {
    id: 'project-1',
    title: 'CareerCompass: AI-Powered Career Mentor',
    description: 'An AI-driven web app for resume analysis, ATS resume building, cover letter generation, and mock interviews.',
    longDescription: 'This project demonstrates a sophisticated, AI-driven web application designed to assist users with career development. It features AI-powered resume analysis, ATS resume building, cover letter generation, and an interactive mock interview simulator with real-time feedback. The focus was on integrating cutting-edge AI capabilities with a professional, responsive user interface.',
    imageUrl: 'https://i.ibb.co/JWt10kzX/6555d160-0091-4b3b-841b-b85e201088c0.png',
    tags: ["Next.js", "React", "TypeScript", "Genkit", "ShadCN UI", "Tailwind CSS", "Firebase", "Full-Stack", "AI Integration"],
    projectUrl: 'https://carrercompassavr.netlify.app/',
    repoUrl: 'https://github.com/amithviswas/career-compass',
    technologies: ["Next.js (App Router)", "React", "TypeScript", "Genkit (Google AI)", "ShadCN UI", "Tailwind CSS", "Firebase"],
    dataAiHint: 'AI career mentor',
  },
  {
    id: 'project-2',
    title: 'Home Theater Experience',
    description: 'A web application simulating a home theater selection and viewing experience.',
    longDescription: 'A web application simulating a home theater selection and viewing experience. Users can explore different setups and features, aiming to provide an immersive preview of home cinema possibilities. Built with foundational web technologies.',
    imageUrl: 'https://i.ibb.co/G52Sq68/Screenshot-of-Home-Theater.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'UI/UX'],
    projectUrl: 'https://amithviswas.github.io/Home-Theater-Experience/',
    repoUrl: '#', // Assuming no public repo or to be updated
    technologies: ['HTML', 'CSS', 'JavaScript'],
    dataAiHint: 'web application',
  },
  {
    id: 'project-3',
    title: 'Reverse-engineered Twitch.tv UI',
    description: 'A recreation of the Twitch.tv user interface focusing on front-end details.',
    longDescription: 'A front-end project aimed at meticulously recreating the Twitch.tv user interface. This exercise focused on attention to detail in UI/UX, implementing complex layouts and styling using HTML and CSS.',
    imageUrl: 'https://i.ibb.co/kqk32SP/Screenshot-of-Twitch-tv.png',
    tags: ['UI/UX', 'HTML', 'CSS', 'Reverse Engineering'],
    projectUrl: 'https://amithviswas.github.io/Twitch.tv-UI-Reversed-Engineered-/',
    repoUrl: '#',
    technologies: ['HTML', 'CSS'],
    dataAiHint: 'website interface',
  },
  {
    id: 'project-4',
    title: 'Music Player with Slider',
    description: 'A functional music player interface with playback controls and a progress slider.',
    longDescription: 'A web-based music player featuring standard playback controls and a dynamic progress slider. This project highlights JavaScript for interactivity and DOM manipulation, along with HTML and CSS for the interface.',
    imageUrl: 'https://i.ibb.co/tp12Hq5/Screenshot-2024-07-09-153458.png',
    tags: ['JavaScript', 'HTML', 'CSS', 'UI Component'],
    projectUrl: 'https://amithviswas.github.io/Music-Player-with-Slider/',
    repoUrl: '#',
    technologies: ['JavaScript', 'HTML', 'CSS'],
    dataAiHint: 'web application',
  },
  {
    id: 'project-5',
    title: 'Dark Run Game',
    description: 'An engaging scroll-based game named Dark Run, built with web technologies.',
    longDescription: 'Dark Run is an engaging scroll-based game developed using web technologies. It showcases game logic implementation with JavaScript and rendering using HTML5 features, possibly Canvas.',
    imageUrl: 'https://i.ibb.co/cNNvz48/Screenshot-2024-07-09-154834.png',
    tags: ['JavaScript', 'HTML5 Game', 'Canvas'],
    projectUrl: 'https://amithviswas.github.io/Scroll-Game-Dark-Run/',
    repoUrl: '#',
    technologies: ['JavaScript', 'HTML', 'CSS', 'Canvas API (potentially)'],
    dataAiHint: 'game interface',
  },
  {
    id: 'project-6',
    title: 'Old Car Game',
    description: 'A retro-style car game developed using web technologies.',
    longDescription: 'A retro-style car game built with fundamental web technologies. This project aims to recreate a classic gaming experience, focusing on JavaScript for game mechanics and simple graphics.',
    imageUrl: 'https://i.ibb.co/6XYKhGP/Screenshot-2024-07-09-105411.png',
    tags: ['JavaScript', 'HTML5 Game', 'Retro'],
    projectUrl: 'https://amithviswas.github.io/Old-Car-Game/',
    repoUrl: '#',
    technologies: ['JavaScript', 'HTML', 'CSS'],
    dataAiHint: 'game interface',
  }
];
